version: 0.2

phases:
  pre_build:
    commands:
      - apt-get update && apt-get install -y python3 python3-pip
      - pip3 install -r requirements.txt
      - python3 manage.py collectstatic --noinput

  build:
    commands:
      - echo "Build started"

  post_build:
    commands:
      - echo "Build completed"
