# Generated by Django 5.0.3 on 2024-05-24 11:38

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer_code', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('mobile_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Hold', 'Hold')], default='Pending', max_length=10)),
                ('Contact', models.CharField(choices=[('No', 'No'), ('Yes', 'Yes')], default='No', max_length=10)),
                ('resume', models.FileField(upload_to='candidate/resume/')),
                ('sector', models.CharField(max_length=50)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.CharField(max_length=50)),
                ('totalCommission', models.CharField(max_length=10)),
                ('Contact_by', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('employee_id', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_secret', models.CharField(max_length=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=15)),
                ('shop_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('refer_code', models.CharField(max_length=10, unique=True)),
                ('date_of_birth', models.TextField(max_length=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('profileVerification', models.CharField(choices=[('Under Process', 'Under Process'), ('Verified', 'Verified'), ('Rejected(Upload Details Again)', 'Rejected(Upload Details Again)')], default='Under Process', max_length=50)),
                ('total_commission_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferredVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referring_vendor', to='EMTA_AWS_APP.vendor')),
                ('referring_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_vendors', to='EMTA_AWS_APP.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_card', models.CharField(max_length=15)),
                ('pan_card', models.CharField(max_length=15)),
                ('adhar_image', models.FileField(upload_to='adhar/')),
                ('pan_image', models.FileField(upload_to='pan/')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EMTA_AWS_APP.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='BussinessDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gumasta', models.FileField(upload_to='Gumasata/')),
                ('gst_number', models.CharField(max_length=20)),
                ('gst_image', models.FileField(upload_to='GST/')),
                ('Bpan_number', models.CharField(max_length=15)),
                ('Bpan_image', models.FileField(upload_to='Bussiness pan card/')),
                ('MSME_number', models.CharField(max_length=15)),
                ('MSME_image', models.FileField(upload_to='MSME/')),
                ('Contact_number', models.CharField(max_length=12)),
                ('Bphoto_outer', models.FileField(upload_to='Bussiness photo/outer')),
                ('Bphoto_inside', models.FileField(upload_to='Bussiness photo/inside')),
                ('Gumasta_number', models.CharField(max_length=15)),
                ('Busness_email', models.EmailField(max_length=50)),
                ('VCname', models.CharField(max_length=50)),
                ('VCmobile', models.CharField(max_length=12)),
                ('VCaddress', models.CharField(max_length=150)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EMTA_AWS_APP.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_document', models.FileField(upload_to='Bank/')),
                ('account_type', models.CharField(blank=True, choices=[('Saving', 'Saving'), ('Current', 'Current')], max_length=100, null=True)),
                ('preffered_payout_date', models.CharField(choices=[('05', '05'), ('15', '15'), ('25', '25')], max_length=10)),
                ('account_holder_name', models.CharField(max_length=50)),
                ('account_number1', models.CharField(max_length=20, null=True)),
                ('ifs_code', models.CharField(max_length=20)),
                ('micr_code', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=20)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EMTA_AWS_APP.vendor')),
            ],
        ),
    ]
