# Generated by Django 5.0.3 on 2024-05-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_type',
            field=models.CharField(choices=[('Saving', 'Saving'), ('Current', 'Current')], max_length=100),
        ),
    ]
