# Generated by Django 5.0.3 on 2024-05-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0002_alter_bank_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussinessdetails',
            name='Busness_email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
