# Generated by Django 5.0.3 on 2024-05-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0003_bussinessdetails_busness_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinessdetails',
            name='Busness_email',
            field=models.EmailField(max_length=50),
        ),
    ]
