# Generated by Django 5.0.3 on 2024-05-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0004_alter_bussinessdetails_busness_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussinessdetails',
            name='VCaddress',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bussinessdetails',
            name='VCmobile',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bussinessdetails',
            name='VCname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
