# Generated by Django 5.0.3 on 2024-05-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0005_bussinessdetails_vcaddress_bussinessdetails_vcmobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Bussiness_year',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
