# Generated by Django 5.0.3 on 2024-07-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0005_remove_candidate_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Remark',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
