# Generated by Django 5.0.3 on 2024-07-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0006_candidate_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='commission_Generate_date',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
