# Generated by Django 5.0.3 on 2024-05-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0006_vendor_bussiness_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='Bussiness_year',
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='Bussiness_year',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
