# Generated by Django 5.0.3 on 2024-05-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0007_remove_vendor_bussiness_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledocument',
            name='Bussiness_year',
        ),
    ]
