# Generated by Django 5.0.3 on 2024-05-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0008_remove_profiledocument_bussiness_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_type',
            field=models.CharField(choices=[('Saving', 'Saving'), ('Current', 'Current')], default='Saving', max_length=100),
        ),
    ]
