# Generated by Django 5.0.3 on 2024-07-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0009_candidate_payment_status_alter_candidate_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Job_Type',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Payment_Status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Under Process', 'Under Process'), ('Hold', 'Hold')], default='Pending', max_length=30),
        ),
    ]
