# Generated by Django 5.0.3 on 2024-05-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0009_alter_bank_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_number1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Saving', 'Saving'), ('Current', 'Current')], max_length=100, null=True),
        ),
    ]
