# Generated by Django 5.0.3 on 2024-05-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0010_alter_bank_account_number1_alter_bank_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='profile_image',
        ),
    ]
