# Generated by Django 5.0.3 on 2024-07-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0010_candidate_job_type_alter_candidate_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='Job_Type',
        ),
    ]
