# Generated by Django 5.0.3 on 2024-07-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0011_remove_candidate_job_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferredVendor',
        ),
    ]
