# Generated by Django 5.0.3 on 2024-07-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0012_delete_referredvendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Job_Type',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
