# Generated by Django 5.0.3 on 2024-07-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0013_candidate_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Payment_complete_date',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
