# Generated by Django 5.0.3 on 2024-07-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0014_candidate_payment_complete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='commission',
            field=models.CharField(max_length=10),
        ),
    ]
