# Generated by Django 5.0.3 on 2024-07-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0018_alter_candidate_totalcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='sagar',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
