# Generated by Django 5.0.3 on 2024-07-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0020_remove_candidate_sagar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='preffered_payout_date',
            field=models.CharField(choices=[('15', '15'), ('30', '30')], max_length=10),
        ),
    ]
