# Generated by Django 5.0.3 on 2024-07-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0021_alter_bank_preffered_payout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='submission_time',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
