# Generated by Django 5.0.3 on 2024-07-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMTA_AWS_APP', '0022_candidate_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='submission_time',
            field=models.CharField(max_length=20),
        ),
    ]
